AspireUni/Aspire

mentorApp/lib/AppController.dart
mentorApp/lib/Chat/Chat.dart
mentorApp/lib/Dashboard/Dashboard.dart
mentorApp/lib/Profile/UserProfile.dart
mentorApp/lib/main.dart
mentorApp/pubspec.lock
mentorApp/pubspec.yaml
mentorApp/test/WidgetTest.dart

**Changes**
- created placeholder screens and nav items for profile, home, and chat screens
- created an AppController to maintain the screen navigation state
- set default navigation item to the center home icon
- upgraded nav bar styling using curved navigation bar package
**UI**
> <img src="https://user-images.githubusercontent.com/23146829/81177634-37916b00-8f64-11ea-9b3d-cef0082cc09b.png" alt="A gif of the curved bottom navigation in the app" width="300px" />

feat: nav bar and screen navigation

---

mentorApp/ios/Flutter/Debug.xcconfig
mentorApp/ios/Flutter/Release.xcconfig
mentorApp/ios/Podfile
mentorApp/pubspec.lock
mentorApp/pubspec.yaml

**Changes**
- added google fonts package 
**UI**
> No visible changes.
**Note**
- UPDATE: Ready to be merged now.
- I did this quickly while working on the navigation task. I forgot to clean my branch and therefore it carries the changes from #11. Is it okay if we merge #11 first and the look at this PR? 😅

chore: add muli typeset from google fonts

---

mentorApp/pubspec.yaml

**Changes**
- upgrade SDK to allow spreading operator
**UI**
> No visible changes.
**Notes**
- UPDATE: Ready for merge.
- Carries the changes from #11 so please look at #11 first. Sorry. 😅

chore: upgrade sdk 

---

mentorApp/ios/Podfile.lock
mentorApp/ios/Runner.xcodeproj/project.pbxproj
mentorApp/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
mentorApp/ios/Runner/GoogleService-Info.plist
mentorApp/lib/main.dart
mentorApp/pubspec.lock
mentorApp/pubspec.yaml

Changes
add firebases set-up file and upgrade the dependency things.
UI
No visible changes.
Notes
https://flutter.dev/docs/development/ios-project-migration
Important to look at this migration documentation when upgrading the flutter for iOS.

chore: add firebase setup for iOS

---

LICENSE

**Changes**
- Adding a standard base level license
**UI**
- No visible changes

chore: create LICENSE.md

---

LICENSE

**Changes**
- Update from MIT license to Apache 2.0 license
**UI**
- No visible changes

feat: update LICENSE

---

.circleci/config.yml

**Changes**
- deleted `travis.yml`
- added a circleci config
**UI**

chore: add .circleci/config.yml

---

lib/chat/chat_messenger.dart
lib/chat/messages.dart
lib/chat/new_matches.dart

**Changes**
- Add Chat Messenger View Page
- Add Interactive TextFormField that pushes to messages upon completion
**UI**
> ![Screen Shot 2020-05-25 at 10 32 51 AM](https://user-images.githubusercontent.com/43127491/82830521-2f499300-9e73-11ea-9cb5-f9e4cdc0d2da.png)

feat: create interactive messenger view

---

lib/constants/profile_constants.dart
lib/profile/sections/contact.dart
lib/profile/sections/sections.dart

**Changes**
- Adds a chat link and corresponding navigation to the user profile page
**UI**
> ![Simulator Screen Shot - iPhone 11 Pro - 2020-06-04 at 22 46 20](https://user-images.githubusercontent.com/43127491/83837992-38c5cd00-a6b5-11ea-8dc5-1a2c741ce9bd.png)

feat: add chat link to user profile page

---

CONTRIBUTING.md
README.md
android/app/build.gradle
android/app/google-services.json
android/app/src/debug/AndroidManifest.xml
android/app/src/main/AndroidManifest.xml
android/app/src/main/kotlin/com/example/mentor_app/MainActivity.kt
android/app/src/profile/AndroidManifest.xml
ios/Runner/GoogleService-Info.plist
ios/Runner/Info.plist
lib/navigation/app_controller.dart
lib/navigation/root.dart
lib/profile/header.dart
lib/profile/sections/contact.dart
lib/profile/sections/education.dart
lib/profile/sections/experience.dart
lib/profile/sections/skills.dart
lib/profile/sections/summary.dart
pubspec.yaml
test/chat/chat_test.dart
test/dashboard/dashboard_test.dart
test/ftu/filters_test.dart
test/ftu/signup_test.dart
test/main_test.dart
test/navigation/app_controller_test.dart
test/navigation/root_test.dart
test/profile/user_profile_test.dart

**Changes**
- updated all references of `mentorApp` to `aspire`
**UI**

chore: rename app to aspire

---

analysis_options.yaml
pubspec.lock
pubspec.yaml

**Changes**
- added `effective_dart` lint package
- added `analysis_options.yaml` lint config file
**UI**
> No visible changes.

chore: add effective dart linter

---

analysis_options.yaml
lib/chat/chat_messenger.dart
lib/pairings/pairings_card.dart
lib/profile/sections/contact.dart
lib/profile/sections/education.dart
lib/profile/sections/experience.dart
lib/profile/sections/skills.dart

**Changes**
- deleted `avoid_positional_boolean_parameters` from error ignore list
- fixed all violations of this lint rule
**UI**

fix: avoid_positional_boolean_parameters errors

---

analysis_options.yaml
lib/pairings/pairings_card.dart
test/chat/chat_test.dart
test/dashboard/dashboard_test.dart
test/ftu/filters_test.dart
test/ftu/signup_test.dart
test/main_test.dart
test/navigation/app_controller_test.dart
test/navigation/root_test.dart
test/profile/user_profile_test.dart

**Changes**
- deleted `avoid_types_on_closure_parameters` from error ignore list
- fixed all violations of this lint rule
**UI**

fix: avoid_types_on_closure_parameters errors

---

analysis_options.yaml
lib/chat/new_matches.dart
lib/chat/user_message_rows.dart
lib/navigation/root.dart

**Changes**
- deleted `directives_ordering` from error ignore list
- fixed all violations of this lint rule
**UI**

fix: directives_ordering errors

---

analysis_options.yaml
lib/chat/chat_messenger.dart
lib/chat/new_matches.dart
lib/chat/user_message_rows.dart
lib/ftu/filters.dart
lib/profile/sections/education.dart
lib/profile/sections/experience.dart
lib/profile/sections/skills.dart

**Changes**
- delete `unnecessary_new` from errors ignore list
- fix all violations of this lint rule
**UI**

fix: unnecessary_new lint errors

---

analysis_options.yaml
lib/profile/header.dart
lib/profile/sections/contact.dart
lib/profile/sections/education.dart
lib/profile/sections/experience.dart
lib/profile/sections/skills.dart
lib/profile/sections/summary.dart

**Changes**
- delete `prefer_relative_imports` from errors ignore list
- fix all violations of this lint rule
**UI**

fix: prefer_relative_imports errors

---

analysis_options.yaml
lib/navigation/app_controller.dart
lib/profile/sections/contact.dart
lib/profile/sections/education.dart
lib/profile/sections/experience.dart

**Changes**
- delete `prefer_final_fields` from errors list
- delete `prefer_interpolation_to_compose_strings` from errors list
- fix all violations of lint rule
**UI**

fix: prefer_final_fields + prefer_interpolation_to_compose_strings

---

analysis_options.yaml
lib/chat/chat_messenger.dart
lib/chat/new_matches.dart
lib/chat/user_message_rows.dart
lib/profile/sections/education.dart
lib/profile/sections/experience.dart
lib/profile/sections/skills.dart

**Changes**
- deleted `prefer_collection_literals` from errors ignore list
- deleted `non_bool_condition` from errors ignore list
- fixed all violations of this lint rule
**UI**

fix: prefer_collection_literals + non_bool_condition errors

---

analysis_options.yaml
lib/chat/chat_messenger.dart
lib/chat/new_matches.dart
lib/chat/user_message_rows.dart
lib/ftu/authentication.dart
lib/ftu/signuplogin.dart
lib/profile/sections/education.dart
lib/profile/sections/experience.dart
lib/profile/sections/section.dart
lib/profile/sections/skills.dart

**Changes**
- fixed any violations of `omit_local_variable_types`
**UI**

fix: omit_local_variable_types errors

---

ios/Podfile
ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj

**Changes**
- Fixes `podfile install` bug
**UI**
> N/A

fix: podfile bug

---

lib/common/footer_links.dart
lib/common/primary_button.dart
lib/constants/ftu_constants.dart
lib/ftu/get_started/intro.dart
lib/ftu/login_create_account/login_create_account.dart
lib/models/states/app_state.dart

**Changes**
- Added Login/Create account page
- Fixed responsiveness bug for Get Started intro page
**UI**
On Phone 11 Pro Max:
> <img src="https://user-images.githubusercontent.com/25041263/88471747-c52c8900-cec9-11ea-8bfb-624873631794.png" width="300"/> <img src="https://user-images.githubusercontent.com/25041263/88471746-c493f280-cec9-11ea-8f58-8e9d9c9bd0af.png" width="300"/>
On iPhone SE:
> <img src="https://user-images.githubusercontent.com/25041263/88471744-c2319880-cec9-11ea-89ed-737821a58007.png" width="300"/> <img src="https://user-images.githubusercontent.com/25041263/88471745-c362c580-cec9-11ea-88a6-5dcc6d0475e3.png" width="300"/>

feat: add login/create account page

---

lib/chat/chat_messenger.dart
lib/chat/common/message_row.dart
lib/chat/new_matches.dart
lib/navigation/app_controller.dart
lib/profile/view_profile/header.dart
lib/profile/view_profile/sections/contact.dart
lib/profile/view_profile/sections/sections.dart
lib/profile/view_profile/user_profile.dart

**Changes**
- Provide UserProfile with a profileId (other than your own ID) to render a view-only UserProfile
- Direct to ChatMessenger from UserProfile
- Direct to UserProfile from ChatMessenger
**UI**
> ![Screen Recording 2020-07-30 at 11 13 16 PM](https://user-images.githubusercontent.com/43127491/89002709-10c0a780-d2bb-11ea-9156-cfc9c96f5d33.gif)

feat: make view-only user profile

---

lib/ftu/onboarding/steps.dart

**Changes**
- Add both SlideIn and SlideOut animations for onboarding steps
**UI**
> ![Screen Recording 2020-08-04 at 3 07 25 PM](https://user-images.githubusercontent.com/43127491/89345369-884c5900-d664-11ea-8ddc-2c6bc8b35a6a.gif)

fix(onboarding): add slide in and out animations
